-- ============================================================================
-- 05_cms_snowflake_feature_engineering.sql
-- Author : Waldo Ketonou
-- CMS Hospital Quality Project
-- Feature Engineering, Validation, and Unified Dataset Creation
-- ============================================================================

-- ============================================================================
-- B. FEATURE ENGINEERING
-- ============================================================================

-- B1. Readmission Index
CREATE OR REPLACE TABLE CMS_PROJECT.CORE.FEAT_READMISSION AS
SELECT
    FACILITY_ID,
    AVG(READMISSION_SCORE) AS READMISSION_INDEX
FROM CMS_PROJECT.STAGING.STG_READMISSION
GROUP BY FACILITY_ID;

-- B2. Mortality Index
CREATE OR REPLACE TABLE CMS_PROJECT.CORE.FEAT_MORTALITY AS
SELECT
    FACILITY_ID,
    AVG(MORTALITY_SCORE) AS MORTALITY_INDEX
FROM CMS_PROJECT.STAGING.STG_MORTALITY
GROUP BY FACILITY_ID;

-- B3. Patient Experience (HCAHPS)
CREATE OR REPLACE TABLE CMS_PROJECT.CORE.FEAT_HCAHPS AS
SELECT
    FACILITY_ID,
    AVG(HCAHPS_SCORE) AS PATIENT_EXPERIENCE_SCORE
FROM CMS_PROJECT.STAGING.STG_HCAHPS
GROUP BY FACILITY_ID;

-- B4. Timely & Effective Care (TEC)
CREATE OR REPLACE TABLE CMS_PROJECT.CORE.FEAT_TEC AS
SELECT
    FACILITY_ID,
    AVG(TEC_SCORE) AS TIMELY_EFFECTIVE_CARE_SCORE
FROM CMS_PROJECT.STAGING.STG_TEC
GROUP BY FACILITY_ID;

-- ============================================================================
-- C. VALIDATION
-- ============================================================================

-- C1. Row Count Validation
SELECT 'FEAT_READMISSION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM CMS_PROJECT.CORE.FEAT_READMISSION
UNION ALL
SELECT 'FEAT_MORTALITY', COUNT(*) FROM CMS_PROJECT.CORE.FEAT_MORTALITY
UNION ALL
SELECT 'FEAT_HCAHPS', COUNT(*) FROM CMS_PROJECT.CORE.FEAT_HCAHPS
UNION ALL
SELECT 'FEAT_TEC', COUNT(*) FROM CMS_PROJECT.CORE.FEAT_TEC;

-- C2. Duplicate Facility Check
SELECT FACILITY_ID, COUNT(*) AS CNT
FROM CMS_PROJECT.CORE.FEAT_READMISSION
GROUP BY FACILITY_ID
HAVING COUNT(*) > 1;

SELECT FACILITY_ID, COUNT(*) AS CNT
FROM CMS_PROJECT.CORE.FEAT_MORTALITY
GROUP BY FACILITY_ID
HAVING COUNT(*) > 1;

SELECT FACILITY_ID, COUNT(*) AS CNT
FROM CMS_PROJECT.CORE.FEAT_HCAHPS
GROUP BY FACILITY_ID
HAVING COUNT(*) > 1;

SELECT FACILITY_ID, COUNT(*) AS CNT
FROM CMS_PROJECT.CORE.FEAT_TEC
GROUP BY FACILITY_ID
HAVING COUNT(*) > 1;

-- C3. NULL Feature Validation
SELECT
    SUM(CASE WHEN R.READMISSION_INDEX IS NULL THEN 1 ELSE 0 END) AS NULL_READMISSION,
    SUM(CASE WHEN M.MORTALITY_INDEX IS NULL THEN 1 ELSE 0 END) AS NULL_MORTALITY,
    SUM(CASE WHEN P.PATIENT_EXPERIENCE_SCORE IS NULL THEN 1 ELSE 0 END) AS NULL_HCAHPS,
    SUM(CASE WHEN T.TIMELY_EFFECTIVE_CARE_SCORE IS NULL THEN 1 ELSE 0 END) AS NULL_TEC
FROM CMS_PROJECT.CORE.CMS_CLEAN_HOSPITAL_QUALITY H
LEFT JOIN CMS_PROJECT.CORE.FEAT_READMISSION R USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_MORTALITY M USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_HCAHPS P USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_TEC T USING (FACILITY_ID);

-- C4. Numeric Range Validation
SELECT
    MIN(R.READMISSION_INDEX) AS MIN_READMISSION,
    MAX(R.READMISSION_INDEX) AS MAX_READMISSION,
    MIN(M.MORTALITY_INDEX) AS MIN_MORTALITY,
    MAX(M.MORTALITY_INDEX) AS MAX_MORTALITY,
    MIN(P.PATIENT_EXPERIENCE_SCORE) AS MIN_HCAHPS,
    MAX(P.PATIENT_EXPERIENCE_SCORE) AS MAX_HCAHPS,
    MIN(T.TIMELY_EFFECTIVE_CARE_SCORE) AS MIN_TEC,
    MAX(T.TIMELY_EFFECTIVE_CARE_SCORE) AS MAX_TEC
FROM CMS_PROJECT.CORE.FEAT_READMISSION R
LEFT JOIN CMS_PROJECT.CORE.FEAT_MORTALITY M USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_HCAHPS P USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_TEC T USING (FACILITY_ID);

-- ============================================================================
-- D. UNIFIED MODELING DATASET
-- ============================================================================

CREATE OR REPLACE TABLE CMS_PROJECT.CORE.CMS_CLEAN_HOSPITAL_QUALITY_FINAL AS
SELECT
    H.FACILITY_ID,
    H.FACILITY_NAME,
    H.ADDRESS,
    H.CITY,
    H.STATE,
    H.ZIP_CODE,
    H.COUNTY_NAME,
    H.PHONE_NUMBER,
    H.HOSPITAL_TYPE,
    H.HOSPITAL_OWNERSHIP,
    H.EMERGENCY_SERVICES,
    H.BIRTHING_FRIENDLY,

    R.READMISSION_INDEX,
    M.MORTALITY_INDEX,
    P.PATIENT_EXPERIENCE_SCORE,
    T.TIMELY_EFFECTIVE_CARE_SCORE,

    CASE
        WHEN H.STATE IN ('ME','NH','VT','MA','RI','CT','NY','NJ','PA') THEN 'Northeast'
        WHEN H.STATE IN ('OH','MI','IN','IL','WI','MN','IA','MO','KS','NE','SD','ND') THEN 'Midwest'
        WHEN H.STATE IN ('DE','MD','DC','VA','WV','NC','SC','GA','FL','KY','TN','MS','AL','AR','LA','OK','TX') THEN 'South'
        WHEN H.STATE IN ('MT','ID','WY','CO','NM','AZ','UT','NV','WA','OR','CA','AK','HI') THEN 'West'
        ELSE 'Unknown'
    END AS STATE_REGION

FROM CMS_PROJECT.CORE.CMS_CLEAN_HOSPITAL_QUALITY H
LEFT JOIN CMS_PROJECT.CORE.FEAT_READMISSION R USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_MORTALITY M USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_HCAHPS P USING (FACILITY_ID)
LEFT JOIN CMS_PROJECT.CORE.FEAT_TEC T USING (FACILITY_ID);

-- Final Validation
SELECT COUNT(*) AS ROWS_IN_FINAL
FROM CMS_PROJECT.CORE.CMS_CLEAN_HOSPITAL_QUALITY_FINAL;

SELECT FACILITY_ID, COUNT(*) AS CNT
FROM CMS_PROJECT.CORE.CMS_CLEAN_HOSPITAL_QUALITY_FINAL
GROUP BY FACILITY_ID
HAVING COUNT(*) > 1;
